In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df = pd.read_csv("student-por.csv", sep=",")
display(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason guardian  traveltime  studytime  failures schoolsup famsup paid activities nursery higher internet romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  course   mother           2          2         0       yes     no   no         no     yes    yes       no       no       4         3      4     1     1       3         4   0  11  11
1     GP   F   17       U     GT3       T     1     1  at_home     other  course   father           1          2         0        no    yes   no         no      no    yes      yes       no       5         3      3     1     1       3         2   9  11  11
2     GP   F   15       U     LE3       T     1     1  at_home     other   other   mother           1          2         0       yes     no   no         no     yes    yes      yes       no       4         3      2     2     3       3         6  12  13  12
3     GP   F   15       U     GT3       T     4     2   health  services    home   mother           1          3         0        no    yes   no        yes     yes    yes      yes      yes       3         2      2     1     1       5         0  14  14  14
4     GP   F   16       U     GT3       T     3     3    other     other    home   father           1          2         0        no    yes   no         no     yes    yes       no       no       4         3      2     1     2       5         0  11  13  13

In [ ]:
df.head()

#Displays the first five records of the dataset.

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason guardian  traveltime  studytime  failures schoolsup famsup paid activities nursery higher internet romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  course   mother           2          2         0       yes     no   no         no     yes    yes       no       no       4         3      4     1     1       3         4   0  11  11
1     GP   F   17       U     GT3       T     1     1  at_home     other  course   father           1          2         0        no    yes   no         no      no    yes      yes       no       5         3      3     1     1       3         2   9  11  11
2     GP   F   15       U     LE3       T     1     1  at_home     other   other   mother           1          2         0       yes     no   no         no     yes    yes      yes       no       4         3      2     2     3       3         6  12  13  12
3     GP   F   15       U     GT3       T     4     2   health  services    home   mother           1          3         0        no    yes   no        yes     yes    yes      yes      yes       3         2      2     1     1       5         0  14  14  14
4     GP   F   16       U     GT3       T     3     3    other     other    home   father           1          2         0        no    yes   no         no     yes    yes       no       no       4         3      2     1     2       5         0  11  13  13

In [ ]:
df.shape

#Shows the number of rows and columns in the dataset.

(649, 33)

In [ ]:
df.tail()

##Displays the last five records of the dataset.

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  reason guardian  traveltime  studytime  failures schoolsup famsup paid activities nursery higher internet romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
644     MS   F   19       R     GT3       T     2     3  services     other  course   mother           1          3         1        no     no   no        yes      no    yes      yes       no       5         4      2     1     2       5         4  10  11  10
645     MS   F   18       U     LE3       T     3     1   teacher  services  course   mother           1          2         0        no    yes   no         no     yes    yes      yes       no       4         3      4     1     1       1         4  15  15  16
646     MS   F   18       U     GT3       T     1     1     other     other  course   mother           2          2         0        no     no   no        yes     yes    yes       no       no       1         1      1     1     1       5         6  11  12   9
647     MS   M   17       U     LE3       T     3     1  services  services  course   mother           2          1         0        no     no   no         no      no    yes      yes       no       2         4      5     3     4       2         6  10  10  10
648     MS   M   18       R     LE3       T     3     2  services     other  course   mother           3          1         0        no     no   no         no      no    yes      yes       no       4         4      1     3     4       5         4  10  11  11

In [ ]:
df.info()

#Provides a summary of the dataset, including column names, data types, and non-null values.

<class 'pandas.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    str
 1   sex         649 non-null    str
 2   age         649 non-null    int64
 3   address     649 non-null    str
 4   famsize     649 non-null    str
 5   Pstatus     649 non-null    str
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    str
 9   Fjob        649 non-null    str
 10  reason      649 non-null    str
 11  guardian    649 non-null    str
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    str
 16  famsup      649 non-null    str
 17  paid        649 non-null    str
 18  activities  649 non-null    str
 19  nursery     649 non-null    str
 20  higher      649 non-null    str
 21  internet    649 non-null    str
 22  romantic    649 non-null    str
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), str(17)
memory usage: 167.4 KB

In [ ]:
df.describe()

#Provides statistical information such as mean, minimum, maximum and standard deviation for numerical columns.

       school  sex         age address famsize Pstatus        Medu        Fedu   Mjob   Fjob  reason guardian  traveltime   studytime    failures schoolsup famsup paid activities nursery higher internet romantic      famrel    freetime       goout        Dalc        Walc      health    absences          G1          G2          G3
count     649  649  649.000000     649     649     649  649.000000  649.000000    649    649     649      649  649.000000  649.000000  649.000000       649    649  649        649     649    649      649      649  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000
unique      2    2         NaN       2       2       2         NaN         NaN      5      5       4        3         NaN         NaN         NaN         2      2    2          2       2      2        2        2         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN
top        GP    F         NaN       U     GT3       T         NaN         NaN  other  other  course   mother         NaN         NaN         NaN        no    yes   no         no     yes    yes      yes       no         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN
freq      423  383         NaN     452     457     569         NaN         NaN    258    367     285      455         NaN         NaN         NaN       581    398  610        334     521    580      498      410         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN
mean      NaN  NaN   16.744222     NaN     NaN     NaN    2.514638    2.306626    NaN    NaN     NaN      NaN    1.568567    1.930663    0.221880       NaN    NaN  NaN        NaN     NaN    NaN      NaN      NaN    3.930663    3.180277    3.184900    1.502311    2.280431    3.536210    3.659476   11.399076   11.570108   11.906009
std       NaN  NaN    1.218138     NaN     NaN     NaN    1.134552    1.099931    NaN    NaN     NaN      NaN    0.748660    0.829510    0.593235       NaN    NaN  NaN        NaN     NaN    NaN      NaN      NaN    0.955717    1.051093    1.175766    0.924834    1.284380    1.446259    4.640759    2.745265    2.913639    3.230656
min       NaN  NaN   15.000000     NaN     NaN     NaN    0.000000    0.000000    NaN    NaN     NaN      NaN    1.000000    1.000000    0.000000       NaN    NaN  NaN        NaN     NaN    NaN      NaN      NaN    1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    0.000000    0.000000    0.000000    0.000000
25%       NaN  NaN   16.000000     NaN     NaN     NaN    2.000000    1.000000    NaN    NaN     NaN      NaN    1.000000    1.000000    0.000000       NaN    NaN  NaN        NaN     NaN    NaN      NaN      NaN    4.000000    3.000000    2.000000    1.000000    1.000000    2.000000    0.000000   10.000000   10.000000   10.000000
50%       NaN  NaN   17.000000     NaN     NaN     NaN    2.000000    2.000000    NaN    NaN     NaN      NaN    1.000000    2.000000    0.000000       NaN    NaN  NaN        NaN     NaN    NaN      NaN      NaN    4.000000    3.000000    3.000000    1.000000    2.000000    4.000000    2.000000   11.000000   11.000000   12.000000
75%       NaN  NaN   18.000000     NaN     NaN     NaN    4.000000    3.000000    NaN    NaN     NaN      NaN    2.000000    2.000000    0.000000       NaN    NaN  NaN        NaN     NaN    NaN      NaN      NaN    5.000000    4.000000    4.000000    2.000000    3.000000    5.000000    6.000000   13.000000   13.000000   14.000000
max       NaN  NaN   22.000000     NaN     NaN     NaN    4.000000    4.000000    NaN    NaN     NaN      NaN    4.000000    4.000000    3.000000       NaN    NaN  NaN        NaN     NaN    NaN      NaN      NaN    5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   32.000000   19.000000   19.000000   19.000000

In [70]:
# Check missing values
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [38]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [39]:
df.dtypes

school          str
sex             str
age           int64
address         str
famsize         str
Pstatus         str
Medu          int64
Fedu          int64
Mjob            str
Fjob            str
reason          str
guardian        str
traveltime    int64
studytime     int64
failures      int64
schoolsup       str
famsup          str
paid            str
activities      str
nursery         str
higher          str
internet        str
romantic        str
famrel        int64
freetime      int64
goout         int64
Dalc          int64
Walc          int64
health        int64
absences      int64
G1            int64
G2            int64
G3            int64
dtype: object

In [40]:
print("Rows and Columns:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

Rows and Columns: (649, 33)
Missing Values: 0
Duplicate Rows: 0

In [ ]:
df.nunique()

#Displays all unique values in a column.

school         2
sex            2
age            8
address        2
famsize        2
Pstatus        2
Medu           5
Fedu           5
Mjob           5
Fjob           5
reason         4
guardian       3
traveltime     4
studytime      4
failures       4
schoolsup      2
famsup         2
paid           2
activities     2
nursery        2
higher         2
internet       2
romantic       2
famrel         5
freetime       5
goout          5
Dalc           5
Walc           5
health         5
absences      24
G1            17
G2            16
G3            17
dtype: int64

EDA — Exploratory Data Analysis

Student Age Analysis

In [43]:
df["age"].value_counts()

age
17    179
16    177
18    140
15    112
19     32
20      6
21      2
22      1
Name: count, dtype: int64

In [ ]:
df["sex"].mode()[0]

#Returns the most frequently occurring value in the sex column.

'F'

Final Grade Analysis

In [47]:
df[["G1", "G2", "G3"]].mean()

G1    11.399076
G2    11.570108
G3    11.906009
dtype: float64

In [ ]:
print("Minimum Age:", df["age"].min())
print("Maximum Age:", df["age"].max())

#Displays the minimum and maximum ages of students in the dataset.

Minimum Age: 15
Maximum Age: 22

In [ ]:
print("Minimum Final Grade:", df["G3"].min())
print("Maximum Final Grade:", df["G3"].max())

#Displays the minimum and maximum final grades of students in the dataset.

Minimum Final Grade: 0
Maximum Final Grade: 19

In [ ]:
print(df["school"].value_counts())

# Displays the number of students in each school.

school
GP    423
MS    226
Name: count, dtype: int64

GroupBy Analysis

In [51]:
df.groupby("sex")["G3"].mean()

sex
F    12.253264
M    11.406015
Name: G3, dtype: float64

In [52]:
df.groupby("school")["G3"].mean()

school
GP    12.576832
MS    10.650442
Name: G3, dtype: float64

In [54]:
df.groupby("school")["absences"].mean()

school
GP    4.215130
MS    2.619469
Name: absences, dtype: float64

In [56]:
df.groupby("studytime")["G3"].mean()

studytime
1    10.844340
2    12.091803
3    13.226804
4    13.057143
Name: G3, dtype: float64

In [57]:
df.groupby("absences")["G3"].mean()

absences
0     12.040984
1     12.416667
2     12.190909
3     10.428571
4     12.010753
5     11.750000
6     12.122449
7     13.000000
8     11.619048
9      9.714286
10    12.238095
11    11.200000
12    10.083333
13    14.000000
14    10.375000
15    11.000000
16    10.300000
18    12.333333
21    11.500000
22     8.000000
24     9.000000
26     8.000000
30    16.000000
32    14.000000
Name: G3, dtype: float64

In [58]:
df.groupby("failures")["G3"].mean()

failures
0    12.510018
1     8.642857
2     8.812500
3     8.071429
Name: G3, dtype: float64

In [ ]:
df.pivot_table(
    values="G3",
    index="school",
    columns="sex",
    aggfunc="mean"
)

#Compares the average final grades by school and gender.

sex             F          M
school
GP      13.004219  12.032258
MS      11.034247   9.950000

In [ ]:
df[["G1", "G2", "G3"]].corr()

#Shows the correlation between the first-period, second-period, and final grades.

          G1        G2        G3
G1  1.000000  0.864982  0.826387
G2  0.864982  1.000000  0.918548
G3  0.826387  0.918548  1.000000

## Key Insights

1. The dataset contains 649 student records and 33 columns.
2. There are no missing values or duplicate records.
3. Students' ages range from 15 to 22 years.
4. The GP school has more students than the MS school.
5. The average final grade differs between the two schools.
6. G2 and G3 grades have a strong positive correlation.

## Conclusion

This project analyzes student performance using Python and Pandas. Data cleaning and exploratory data analysis were performed to understand student details, school distribution, study time, absences, and academic grades. The analysis helped identify patterns and relationships in student performance.